@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYmMiLCJleHAiOjE3NDI4NTY1MDB9.fYTrOduRu3-w1q7Jks3TGcqCBTeAGrK57AydFZ5KVs0

#Julio Cesar Ramos
POST http://127.0.0.1:8000/cliente/ HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "nome": "Julio Cesar Ramos Pereira Junior",
    "cpf": "12345678974",
    "telefone": "11987654376"
}