POST http://127.0.0.1:8000/produto/ HTTP/1.1
content-type: application/json

{
    "nome_produto": "Hambúrguer Clássico",
    "descricao": "Hambúrguer com carne 180g, queijo cheddar, alface, tomate e maionese",
    "valor_unitario": 25.90
}